### ISSUE TITLE
Plugin not working in UE 5.4.4

### ISSUE THREAD

**Issue by DigiFalk** [game-fuse/game-fuse-cpp#2]
When installing form marketplace (fab.com) and activating, it requires to restart, when restarting it says its the wrong engine. checked here for the update zo replaced the old version with the newest version on github. Now it says its build for diffrent Engine version and can only be build using IDE, after pressing ok, nothing happens and project wil not get started. 1st 3 images are after downloading from Fab, 4rd image is after updating using latest version on github.
![Schermafbeelding 2024-10-24 155506](https://github.com/user-attachments/assets/bde047a4-577d-4e88-b127-9a82b2d7bb19)
![Schermafbeelding 2024-10-24 155517](https://github.com/user-attachments/assets/34172d80-60ca-4dbe-8f38-f1cf6143e70c)
![Schermafbeelding 2024-10-24 155521](https://github.com/user-attachments/assets/ec8ef05b-4f8e-4906-a8e2-988b68bbb54c)
![Schermafbeelding 2024-10-24 155616](https://github.com/user-attachments/assets/7fd4392a-f6be-494b-8143-21451b7f8693)

**Comment by mitchmeyer1** [comment]
Hello!
Please download the newest build here:
https://github.com/game-fuse/game-fuse-cpp/releases/tag/2.2.6

The newest build is still in the approval process for the Unreal Store currently. Hopefully this is updated soon. Let me know if there are any issues

Cheers
Mitch

**Comment by DigiFalk** [comment]
> Hello! Please download the newest build here: https://github.com/game-fuse/game-fuse-cpp/releases/tag/2.2.6
> 
> The newest build is still in the approval process for the Unreal Store currently. Hopefully this is updated soon. Let me know if there are any issues
> 
> Cheers Mitch

When i use 2.2.6 i get the error message from the last image and the engine wont start until i remove the plugin from the engine and thereby forcing the plugin do be disabled from the project.

**Comment by mitchmeyer1** [comment]
Just to confirm did you download the "prebuilt binaries" zip? Thats the one you can import directly into your project

**Comment by DigiFalk** [comment]
> Just to confirm did you download the "prebuilt binaries" zip? Thats the one you can import directly into your project

ehh to be honest im not an expert in UE yet, you mean i can extract the .zip insinde my project  Main Project folder -> Plugins -> Gamefuse?  or do you mean i have to place it in the plugins folder of the engine

**Comment by tomgiagtz** [comment]
Yes please extract the .zip to `YourProject/Plugins/GameFuse`, this will install the plugin to your project. 

Your directory should look something like this.
```
YourProject
==> YourProject.uproject
==> /Content
==> /Plugins
====> /GameFuse
======> GameFuse.uplugin
======> /Binaries
======> /Intermediate
======> . . . . . 
```
You should remove the plugin from your engine until the Fab.com version is updated, we'll reply here when that happens.

Once Fab.com is updated with this new version, and you install it, that will automatically go into your engine plugins. Then you will be able to remove the `Plugins/GameFuse` folder from your project, and receive updates through Epic Launcher.

**Comment by DigiFalk** [comment]
Ok so i got it inside my project and can call upon it but now when i do the sign up mode (like explained in [https://docs.gamefuse.co/Blueprints%20Unreal/signing%20game%20users%20up/] but the nodes im getting are not the same as the example

**Comment by DigiFalk** [comment]
Also when only activated the plugin i get an error when packaging the project: "UATHelper: Packaging (Android (ASTC)): LogTemp: Error: GameFuse ====> StartupModule
PackagingResults: Error: GameFuse ====> StartupModule"

**Comment by tomgiagtz** [comment]
> Ok so i got it inside my project and can call upon it but now when i do the sign up mode (like explained in [https://docs.gamefuse.co/Blueprints%20Unreal/signing%20game%20users%20up/] but the nodes im getting are not the same as the example

Which nodes are different? SetUpGame shows the incorrect node on the docs, it should look like this:
[GameFuse SetUpGame Example](https://blueprintue.com/blueprint/5t4v_jl1/)
I will update those docs shortly. 

The red nodes are custom events created in the Blueprint, you will need to recreate them in order to respond to the SignUp Completion Callback event.

Screenshots and errors are a great way for me to help as well!

> Also when only activated the plugin i get an error when packaging the project: "UATHelper: Packaging (Android (ASTC)): LogTemp: Error: GameFuse ====> StartupModule PackagingResults: Error: GameFuse ====> StartupModule"

This is looking like separate issue on our side, thank you for finding it! On first glance it should be an easy fix, but will require an update. Are you packaging for Android?

**Comment by DigiFalk** [comment]
I found out that i have the game connected since i get return values from the game variables, so that part is working, the only thing i find (besides the Build error) when i creat the sign up function and when click on the sighn up button it crashes the engine

**Comment by tomgiagtz** [comment]
What error do you get when the engine crashes?

**Comment by EindeVerhaal** [comment]
ow i think its becource i was expecting a popup with a sign up table haha, how do i get input to the Nodes of the sign up ?

**Comment by DigiFalk** [comment]
> What error do you get when the engine crashes?

the following error code (When trying to sign up):


LoginId:fdfe80da45d208dba6662da94396dc7b
EpicAccountId:31d6d03cd032477b98053ceda5702af9

Assertion failed: Object.IsValid() != false [File:G:\Program Files\Epic Games\UE_5.4\Engine\Source\Runtime\Core\Public\UObject\ScriptDelegates.h] [Line: 432] ProcessDelegate() called with no object bound to delegate!

UnrealEditor_GameFuse!FGameFuseAPIResponseCallback_DelegateWrapper() [G:\Temp\HostProject\Plugins\GameFuse\Intermediate\Build\Win64\UnrealEditor\Inc\GameFuse\UHT\APIResponseManager.gen.cpp:76]
UnrealEditor_GameFuse!`UUserAPIManager::SignUp'::`2'::<lambda_1>::operator()() [G:\Temp\HostProject\Plugins\GameFuse\Source\GameFuse\Private\Models\UserAPIManager.cpp:33]
UnrealEditor_GameFuse!TBaseFunctorDelegateInstance<void __cdecl(TSharedPtr<IHttpRequest,1>,TSharedPtr<IHttpResponse,1>,bool),FDefaultTSDelegateUserPolicy,`UUserAPIManager::SignUp'::`2'::<lambda_1> >::ExecuteIfSafe() [G:\Program Files\Epic Games\UE_5.4\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:868]
UnrealEditor_HTTP
UnrealEditor_HTTP
UnrealEditor_HTTP
UnrealEditor_HTTP
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

**Comment by tomgiagtz** [comment]
> ow i think its becource i was expecting a popup with a sign up table haha, how do i get input to the Nodes of the sign up ?

That is up to you! If you'd like to see an example of how it can be done, I'd strongly recommend you have a look at our
[example Unreal project](https://github.com/game-fuse/game-fuse-unreal-example).

The code related to Signing Up is in the GUIApplication/GUI/WBP_SignUp blueprint. Make sure to look at the Graph (Top Right) to find that call to SignUp. It looks like this: https://blueprintue.com/blueprint/rpej2u3g/

**Comment by tomgiagtz** [comment]
> > What error do you get when the engine crashes?
> 
> the following error code (When trying to sign up):
>  ```
> LoginId:fdfe80da45d208dba6662da94396dc7b EpicAccountId:31d6d03cd032477b98053ceda5702af9
> 
> Assertion failed: Object.IsValid() != false [File:G:\Program Files\Epic Games\UE_5.4\Engine\Source\Runtime\Core\Public\UObject\ScriptDelegates.h] [Line: 432] ProcessDelegate() called with no object bound to delegate!
> 
> UnrealEditor_GameFuse!FGameFuseAPIResponseCallback_DelegateWrapper() [G:\Temp\HostProject\Plugins\GameFuse\Intermediate\Build\Win64\UnrealEditor\Inc\GameFuse\UHT\APIResponseManager.gen.cpp:76] UnrealEditor_GameFuse!`UUserAPIManager::SignUp'::`2'::<lambda_1>::operator()() [G:\Temp\HostProject\Plugins\GameFuse\Source\GameFuse\Private\Models\UserAPIManager.cpp:33] UnrealEditor_GameFuse!TBaseFunctorDelegateInstance<void __cdecl(TSharedPtr<IHttpRequest,1>,TSharedPtr<IHttpResponse,1>,bool),FDefaultTSDelegateUserPolicy,`UUserAPIManager::SignUp'::`2'::<lambda_1> >::ExecuteIfSafe() [G:\Program Files\Epic Games\UE_5.4\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:868] UnrealEditor_HTTP UnrealEditor_HTTP UnrealEditor_HTTP UnrealEditor_HTTP UnrealEditor_Core UnrealEditor_Core UnrealEditor_Core UnrealEditor_Core UnrealEditor_Core UnrealEditor_Core UnrealEditor_Core UnrealEditor UnrealEditor UnrealEditor UnrealEditor UnrealEditor UnrealEditor kernel32 ntdll ```

This looks to be upset that there was a bad Callback.
Do you have a red wire connecting to the completion callback on the SignUp node?

**Comment by DigiFalk** [comment]
Gonna check tomorrow, rid not realise there was een example project. TY

**Comment by DigiFalk** [comment]
With the demo project in mind and the temporarly plugin fix i seem to have it working right now

**Comment by tomgiagtz** [comment]
> With the demo project in mind and the temporarly plugin fix i seem to have it working right now

The version fixing your packaging error error has been pushed to Fab.com and has been approved. I'm still waiting to see an update through Fab, but once you get it, you will need to remove the Plugins folder from your projects. Alternatively, our [releases](https://github.com/game-fuse/game-fuse-cpp/releases/tag/2.2.7) page has that update with PreBuilt Binaries, if you don't care to wait!

Closing this out but feel free to message on our [Discord](https://discord.gg/xvYEfrdDqg) if you have further questions about using GameFuse!
